import nodemailer from 'nodemailer';

type EmailPayload = {
  to: string;
  subject: string;
  html: string | any;
};

// Replace with your SMTP credentials
const smtpOptions = {
  host: 'smtp.ethereal.email',
  port: 587,
  secure: false,
  auth: {
    user: 'g3c5233rltgp6l4g@ethereal.email',
    pass: 'NYVVqKa2MmZprpF3Dx',
    // user: process.env.EMAIL_USER, // 'zvnve7bukpcdsgpx@ethereal.email', // example of generated by Mailtrap
    // pass: process.env.EMAIL_PASS // 'QNTZPrJgV6Nd95Agmb' // example of generated by Mailtrap
  },
};

const sendEmail = async (data: EmailPayload) => {
  const transporter = nodemailer.createTransport({
    // service: 'gmail',
    ...smtpOptions,
  });

  return transporter
    .sendMail({
      from: 'info@ai.com',
      ...data,
    })
    .then((info) => {
      // eslint-disable-next-line no-console
      console.log(`Preview URL: ${nodemailer.getTestMessageUrl(info)}`);
    });
};
export default sendEmail;
